server:
  port: 7070
  connection-timeout: 120000

spring:
  datasource:
    url: jdbc:mysql://10.222.49.18:3306/easy_load
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  activemq:
    broker-url: tcp://10.222.49.18:61616?wireFormat.maxInactivityDuration=0
    in-memory: true
    pool:
      enabled: false
    user: admin
    password: admin
  jpa:
    show-sql: false
    database: MySQL
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    com.oocl.easyload: DEBUG

easyload:
  constance:
    host: http://zhangle6-w10:7777